### ISSUE TITLE
This method doesn't work on macOS Catalina

### ISSUE THREAD

**Issue by makeavish** [tekfyl/bits-stdc-.h-for-mac#1]
Please update your readme so that it works on Catalina.

**Comment by ziyaddin** [comment]
Correct, the filepath of `stdc++.h` should be:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/bits
```

**Comment by PalashBansal** [comment]
> Correct, the filepath of `stdc++.h` should be:
> 
> ```
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/bits
> ```

I would suggest to create a PR on readme for the same.

**Comment by makeavish** [comment]
I have created a new repo where I have explained a new method to get bits-stdc++.h and this works even after Mac update.
Repo link: [github.com/makeavish/bits-stdc-.h-for-mac](github.com/makeavish/bits-stdc-.h-for-mac)
